### ISSUE TITLE
Failed to activate the japanese-menu package

### ISSUE THREAD

**Issue by yoshikawa** [syon/atom-japanese-menu#16]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Unknown Windows Version
**Thrown From**: [japanese-menu](https://github.com/syon/atom-japanese-menu) package, v1.7.0
### Stack Trace

Failed to activate the japanese-menu package

```
At Cannot find module 'cson'

Error: Cannot find module 'cson'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\Users\千秋\AppData\Local\atom\app-1.7.3\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\Users\千秋\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/千秋/.atom/packages/japanese-menu/lib/main.coffee:1:15)
    at Object.<anonymous> (file:///C:/Users/千秋/.atom/packages/japanese-menu/lib/main.coffee:1:1)
    at Module._compile (C:\Users\千秋\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\千秋\AppData\Local\atom\app-1.7.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\千秋\AppData\Local\atom\app-1.7.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\千秋\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:715:27)
    at Package.module.exports.Package.activateNow (C:\Users\千秋\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:173:16)
    at C:\Users\千秋\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\千秋\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:92:15)
    at C:\Users\千秋\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\千秋\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\千秋\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\千秋\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (C:\Users\千秋\AppData\Local\atom\app-1.7.3\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\千秋\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\千秋\AppData\Local\atom\app-1.7.3\resources\app.asar\src\package-manager.js:497:46)
    at C:\Users\千秋\AppData\Local\atom\app-1.7.3\resources\app.asar\src\atom-environment.js:754:28
```
### Commands

```
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
japanese-menu, v1.7.0

# Dev
No dev packages
```

**Comment by lunarxlark** [comment]
ユーザ名に2byte文字が含まれると、本エラーが吐かれることが報告済です。

**Comment by syon** [comment]
#8 と同じですね。そろそろ真面目に対応を検討します…。

**Comment by lunarxlark** [comment]
他の言語(ドイツ語のёとか)、他のパッケージでも起きているのでatomの対応待ちでもいいと思います。

Nice package!
Thanks, syon :)

**Comment by syon** [comment]
## Atom のエラーからここにたどり着いた方へ

上記のエラー発生環境にてインストールが成功しましたのでご報告します。

直前のリリースである japanese-menu (v1.10.0) にて `cson` 依存を除去しましたが、エラー発生状態のままアップデートしても直りませんでした。そこで、以下の操作を試したところ成功しました。

- コントロールパネルから Atom をアンインストール
- https://atom.io から最新のインストーラを入手
- Atom をインストール
- 設定画面にてパッケージ japanese-menu をアンインストール
- 設定画面にてパッケージ japanese-menu をインストール

なお、一連の操作を行うにあたって、下記のフォルダを見張っていました。
Atom 本体をアンインストールしても残るものもありますので、ご参考まで。

- `C:\Users\syon\AppData\Local\atom`
- `C:\Users\syon\.atom\.apm`
- `C:\Users\syon\.atom\packages`

※Windowsのユーザ名が syon の場合の例です
