### ISSUE TITLE
Failed to load the japanese-menu package

### ISSUE THREAD

**Issue by akiko-o** [syon/atom-japanese-menu#8]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Unknown Windows Version
**Thrown From**: [japanese-menu](https://github.com/syon/atom-japanese-menu) package, v1.4.0
### Stack Trace

Failed to load the japanese-menu package

```
At Cannot find module 'cson'

Error: Cannot find module 'cson'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\晶紀子\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at new JapaneseMenu (C:\Users\晶紀子\.atom\packages\japanese-menu\lib\main.coffee:4:12)
    at Object.<anonymous> (C:\Users\晶紀子\.atom\packages\japanese-menu\lib\main.coffee:230:44)
    at Object.<anonymous> (C:\Users\晶紀子\.atom\packages\japanese-menu\lib\main.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\晶紀子\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
japanese-menu, v1.4.0
japanese-wrap, v0.2.7

# Dev
No dev packages
```

**Comment by suusanex** [comment]
This is because the 2-byte characters is included in %userprofile%.

PowerShell でユーザー名と異なる userフォルダを自由に設定する - tech.guitarrapc.cóm
http://tech.guitarrapc.com/entry/2013/10/27/061208

**Comment by syon** [comment]
@akiko-o ちょっと見てみます。
@suusanex 情報ありがとうございます。

**Comment by syon** [comment]
ひらがな、漢字でユーザーアカウントを作って Atom をインストールし直し、本パッケージのインストールを試してみました。結果、正常にインストールできてしまいました。
2件の issue を見るとどちらも`System: Unknown Windows Version`であり、OS 依存の事象かもしれません。今後は Windows 10 に収束していくので、ひとまずは静観しようかと思います。

環境: Windows 10 Pro 64bit
cc @lunarxlark  #16

**Comment by syon** [comment]
情けないことに、自分も同じ問題に遭遇してしまいました。
特筆すべき状況としては、以下の通りです。

- 久しぶりに起動した Windows 10 マシンにて
- すでにAtomがインストールされた状態のまま
- 改めて atom.io からインストーラをダウンロードして実行
- すぐさま japanese-menu をインストール実行、エラー発生

--------

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [japanese-menu](https://github.com/syon/atom-japanese-menu) package 1.9.0


### Stack Trace

<details>
  <summary>Failed to activate the japanese-menu package</summary>

```
At Invalid or unexpected token

SyntaxError: Invalid or unexpected token
    at Module._compile (/app.asar/src/native-compile-cache.js:79:40)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/japanese-menu/node_modules/extract-opts/index.js:3:18)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/japanese-menu/node_modules/cson/out/lib/cson.js:9:28)
    at /packages/japanese-menu/node_modules/cson/out/lib/cson.js:410:4)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/japanese-menu/lib/main.coffee:1:15)
    at /packages/japanese-menu/lib/main.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

### Commands

```
```

### Non-Core Packages

```
japanese-menu 1.9.0 
```
</details>

**Comment by syon** [comment]
japanese-menu パッケージのコードで本件に関与しているのは、いずれも `cson` まわりのようです。
これを使わない方式を検討して他のモジュールに依存しないコードとすることで問題の回避を試みます。

**Comment by syon** [comment]
上記のエラー発生環境にてインストールが成功しましたのでご報告します。

直前のリリースである japanese-menu (v1.10.0) にて `cson` 依存を除去しましたが、エラー発生状態のままアップデートしても直りませんでした。そこで、以下の操作を試したところ成功しました。

- コントロールパネルから Atom をアンインストール
- https://atom.io から最新のインストーラを入手
- Atom をインストール
- 設定画面にてパッケージ japanese-menu をアンインストール
- 設定画面にてパッケージ japanese-menu をインストール

なお、一連の操作を行うにあたって、下記のフォルダを見張っていました。
Atom 本体をアンインストールしても残るものもありますので、ご参考まで。

- `C:\Users\syon\AppData\Local\atom`
- `C:\Users\syon\.atom\.apm`
- `C:\Users\syon\.atom\packages`
